name: doctor-slot-check

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install
        run: pip install requests

      - name: debug start
        run: echo "START OK"

      - name: run script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py

      - name: debug end
        run: echo "END OK"
